  # ==========================================================================
# Golang Pre-Commit Hooks | https://github.com/tekwizely/pre-commit-golang
#
# !! ALL Hooks enabled by default - Comment out hooks you are not using
#
# Visit the project home page to learn more about the available Hooks,
# including useful arguments you might want to pass into them.
#
# NOTE: When passing options to hooks, if your options contain a reference
#       to an existing file, then you will need to use a trailing '--'
#       argument to separate the hook options from the modified-file list
#       that Pre-Commit passes into the hook.
#       For repo-based hooks, '--' is not needed.
#
# NOTE: You can pass environment variables to hooks using args with the
#       following format:
#
#           --hook:env:NAME=VALUE
#
# Consider adding aliases to longer-named hooks for easier CLI usage.
# ==========================================================================
repos:
  -   repo: https://github.com/tekwizely/pre-commit-golang
      rev: v1.0.0-rc.1
      hooks:
        #
        # Go Build
        #
        -   id: go-build-mod
        -   id: go-build-repo-mod
        #
        # Go Mod Tidy
        #
        -   id: go-mod-tidy
        -   id: go-mod-tidy-repo
        #
        # Go Test
        #
        -   id: go-test-mod
        -   id: go-test-repo-mod
        #
        # Go Vet
        #
        -   id: go-vet-mod
        -   id: go-vet-repo-mod
        #
        # Revive
        #
        -   id: go-revive
        -   id: go-revive-mod
        -   id: go-revive-repo-mod
        #
        # GoSec
        #
        -   id: go-sec-mod
        #
        # StaticCheck
        #
        -   id: go-staticcheck-mod
        -   id: go-staticcheck-repo-mod
        #
        # StructSlop
        #
        -   id: go-structslop-mod
        -   id: go-structslop-repo-mod
        #
        # Formatters
        #
        -   id: go-fmt
        -   id: go-fmt-repo
        -   id: go-fumpt        # replaces go-fmt
            args: [-w]
        -   id: go-fumpt-repo   # replaces go-fmt-repo
            args: [-w]
        -   id: go-imports      # replaces go-fmt
            args: [-w]
        -   id: go-imports-repo # replaces go-fmt-repo
            args: [-w]
        -   id: go-returns      # replaces go-imports & go-fmt
            args: [-w]
        -   id: go-returns-repo # replaces go-imports-repo & go-fmt-repo
            args: [-w]
        #
        # Style Checkers
        #
        -   id: go-lint
        -   id: go-critic
        #
        # GolangCI-Lint
        # - Fast Multi-Linter
        # - Can be configured to replace MOST other hooks
        # - Supports repo config file for configuration
        # - https://github.com/golangci/golangci-lint

        -   id: golangci-lint-mod
        -   id: golangci-lint-repo-mod